In [1]:
import pandas as pd
import numpy as np
import math
from math import sqrt
import tensorflow as tf
from matplotlib import pyplot as plt
from keras.models import Model, load_model # for creating a Neural Network Autoencoder model
from keras.layers import Dense # for adding layers to AE model
from tensorflow.keras.utils import plot_model #for plotting  model charts
from tensorflow.keras import models,layers,activations,losses,optimizers,metrics
from sklearn.preprocessing import StandardScaler, MinMaxScaler,RobustScaler
from keras import regularizers
from sklearn.model_selection import train_test_split,cross_validate
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor

In [2]:
train_data = pd.read_pickle("EDA_train_mean.pkl")
test_data = pd.read_pickle("EDA_test_mean.pkl")

In [3]:
train_data

wind_speed(m/s)  atmospheric_temperature(°C)  shaft_temperature(°C)  \
0            94.820023                    19.601968              41.723019   
1           241.832734                    27.764785              44.646891   
2            95.484724                    19.601968              41.855473   
3           238.819424                    19.601968              45.443914   
4            10.722890                    19.601968              41.981183   
...                ...                          ...                    ...   
28195        94.765699                    23.576793              45.399352   
28196        94.196738                    24.034329              42.068979   
28197        94.160463                    28.674296              45.004213   
28198        95.430377                    26.560254              48.032624   
28199        43.558352                    18.721231               9.220208   

       blades_angle(°)  gearbox_temperature(°C)  engine_temperature(°C)  \
0            21.025027                82.410573               42.523015   
1            21.025027                44.104919               46.258870   
2            12.652763                42.322098               42.878552   
3            15.115323                44.759643               47.282101   
4             1.715696                51.539405               43.469852   
...                ...                      ...                     ...   
28195         5.377222                51.539405               48.528248   
28196        21.025027                44.285153               43.487939   
28197         9.550358                49.377706               44.042632   
28198         3.051389                81.443896               44.821365   
28199         2.593639                40.262279               40.901975   

       atmospheric_pressure(Pascal)  windmill_body_temperature(°C)  \
0                     103402.961872                      44.275480   
1                      17030.904078                      44.275480   
2                      16125.927107                      45.033197   
3                      18689.732336                      44.827154   
4                     114468.169007                      44.275480   
...                             ...                            ...   
28195                  19428.725079                      44.242269   
28196                  16596.485400                      43.616412   
28197                  19083.881449                      43.576510   
28198                  18360.785707                      44.973415   
28199                 100922.634892                      44.100782   

       wind_direction(°)  rotor_torque(N-m)  ...  turbine_status_BBB  \
0             239.836388          42.084666  ...                 0.0   
1             337.944723         107.888643  ...                 0.0   
2             227.850294          33.069109  ...                 0.0   
3             492.081520          42.744596  ...                 0.0   
4             259.274601          13.387289  ...                 0.0   
...                  ...                ...  ...                 ...   
28195         536.153413          45.909054  ...                 0.0   
28196         354.239825          36.974913  ...                 0.0   
28197         534.209913          88.319152  ...                 0.0   
28198         568.504898          47.562627  ...                 0.0   
28199         320.498070          33.069109  ...                 1.0   

       turbine_status_BCB  turbine_status_BD  turbine_status_D  month   day  \
0                     0.0                0.0               0.0    8.0   4.0   
1                     0.0                0.0               0.0   11.0   5.0   
2                     0.0                0.0               0.0    9.0  14.0   
3                     0.0                0.0               0.0   12.0  25.0   
4                     0.0                0.0               0.0    5.

In [4]:
test_data

wind_speed(m/s)  atmospheric_temperature(°C)  shaft_temperature(°C)  \
0            94.324266                    17.641186              89.714193   
1            10.088870                    13.978119              43.272846   
2           347.152090                    31.423035              41.076640   
3            24.471997                    19.640217              14.375078   
4            96.997026                    33.281836              41.405192   
...                ...                          ...                    ...   
12081        82.587461                    18.517204              43.545409   
12082        97.594116                    19.640217              44.747916   
12083        16.186805                     8.109976              43.252012   
12084        93.254033                    19.640217              43.841789   
12085        42.607485                    13.245828              43.480982   

       blades_angle(°)  gearbox_temperature(°C)  engine_temperature(°C)  \
0            51.146788                40.460560               39.594734   
1            46.516394                40.027788               41.176860   
2            26.931602                43.109122               43.439556   
3            66.513953                13.741253               15.577472   
4             1.843112               121.572907               43.934587   
...                ...                      ...                     ...   
12081        20.992944                44.550547               44.486619   
12082         1.750553                43.308176               42.848779   
12083        20.992944               214.904165               41.177782   
12084        20.992944                41.976913               42.039796   
12085         9.258178               132.587960               46.312684   

       atmospheric_pressure(Pascal)  windmill_body_temperature(°C)  \
0                      16681.044117                      43.756693   
1                     101631.734137                      42.728174   
2                     214812.836175                      43.256122   
3                     101631.734137                      13.501595   
4                      16833.546517                      44.199939   
...                             ...                            ...   
12081                  17239.345506                      42.128526   
12082                  17131.448669                      47.353528   
12083                 118707.643665                      41.768478   
12084                  17155.269313                      82.750271   
12085                 130018.594173                      97.070812   

       wind_direction(°)  rotor_torque(N-m)  ...  turbine_status_BB  \
0             445.976992          21.912243  ...                0.0   
1             499.595287          33.456255  ...                0.0   
2             245.432231          27.195302  ...                0.0   
3             308.376140          15.245757  ...                0.0   
4             442.425744          34.257024  ...                0.0   
...                  ...                ...  ...                ...   
12081         509.795489          33.456255  ...                0.0   
12082         345.705839          33.456255  ...                0.0   
12083         205.569627          12.331790  ...                0.0   
12084         260.578999          33.456255  ...                0.0   
12085         308.376140          19.467561  ...                0.0   

       turbine_status_BBB  turbine_status_BCB  turbine_status_BD  \
0                     0.0                 0.0                0.0   
1                     0.0                 0.0                0.0   
2                     0.0                 0.0                0.0   
3                     1.0                 0.0                0.0   
4                     0.0                 0.0                0.0   
...                   ...                 ...                ...   

In [5]:
y = train_data['windmill_generated_power(kW/h)']
train_data.drop(['windmill_generated_power(kW/h)'], axis=1, inplace = True)

In [6]:
#split dataset 
X_train, X_test, y_train, y_test = train_test_split(train_data, y, random_state=0)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((21055, 33), (21055,), (7019, 33), (7019,))

In [7]:
# declare the steps in our pipeline
from sklearn.ensemble import RandomForestRegressor
my_pipeline = Pipeline([
    ('rf', RandomForestRegressor(n_estimators=100, min_samples_leaf=5, random_state=42))])

In [8]:
# fit the pipeline to our training data
my_pipeline.fit(X_train, y_train)

Pipeline(steps=[('rf',
                 RandomForestRegressor(min_samples_leaf=5, random_state=42))])

In [9]:
# Use cross-validation to estimate the performance of the pipeline
#AT CV = 5
cvs = cross_val_score(my_pipeline, X_train, y_train, cv=5,scoring='neg_mean_absolute_error')
scores_cvs = -1 * cvs

In [10]:
print("MAE scores:\n", scores_cvs)
print('Average MAE score:', scores_cvs.mean())

MAE scores:
 [0.5132855  0.50547362 0.52060514 0.53601026 0.52439178]
Average MAE score: 0.5199532612090465


In [11]:
# Use cross-validation to estimate the performance of the pipeline
#AT CV = 5
cvs_rmse = cross_val_score(my_pipeline, X_train, y_train, cv=5,scoring='neg_root_mean_squared_error')
scores_cvs_rmse = -1 * cvs_rmse

In [12]:
print("RMSE scores:\n", scores_cvs_rmse)
print('Average RMSE score:',scores_cvs_rmse.mean())

RMSE scores:
 [0.83718521 0.81239838 0.85894164 0.89696093 0.86322159]
Average RMSE score: 0.8537415517250799


In [13]:
# Use cross-validation to estimate the performance of the pipeline
#AT CV = 5
cvs_mse = cross_val_score(my_pipeline, X_train, y_train, cv=5,scoring='neg_mean_squared_error')
scores_cvs_mse = -1 * cvs_mse

In [14]:
print("MSE scores:\n", scores_cvs_mse)
print('Average MSE score:',scores_cvs_mse.mean())

MSE scores:
 [0.70087908 0.65999114 0.73778073 0.80453891 0.74515152]
Average MSE score: 0.7296682764399914


### Mean absolute error, Root mean squared error and Mean squared error

In [15]:
# Make predictions on the testing data
y_pred = my_pipeline.predict(X_test)

# Calculate the mean absolute error (MAE)
mae = mean_absolute_error(y_test, y_pred)

# Calculate the mean squared error (MSE)
mse = mean_squared_error(y_test, y_pred)

# Calculate the root mean squared error (RMSE)
rmse = mean_squared_error(y_test, y_pred, squared=False)

# Print the results
print(f"MAE: {mae:.5f}")
print(f"MSE: {mse:.5f}")
print(f"RMSE: {rmse:.5f}")

MAE: 0.51514
MSE: 0.69196
RMSE: 0.83184


In [16]:
# Multiply by -1 since sklearn calculates *negative* MAE
scores_cv = -1 * cross_val_score(my_pipeline, train_data, y, cv=5, scoring='neg_mean_absolute_error')
print("MAE scores:\n", scores_cv)
print('Average MAE score:',scores_cv.mean())

MAE scores:
 [0.51146188 0.52401064 0.50393809 0.51002806 0.51432992]
Average MAE score: 0.5127537177871301
